### ISSUE TITLE
[Question] Use of Garden of Glass

### ISSUE THREAD

**Issue by Ravin890** [cScotPlay/Primal-Skies#27]
I was curious of what the use of garden of glass as opposed to void island control was since you aren't even using the default island from garden of glass

**Comment by cScotPlay** [comment]
I'll have to enlist KiwiFrogg for the specifics as it was all directly related to getting server files to play nicely.  Without Garden of Glass (GoG), we needed to add an additional three mods to the pack to get what GoG could do and we wanted it to say fairly small.  Ultimately, one of the implied goals of the pack was to have a sustainable server that we could play on and have available for all.

**Comment by Ravin890** [comment]
<- questions the things GoG could do was

**Comment by cScotPlay** [comment]
Short answer - "Aside from allowing you to have a skyblock world, a few items and blocks are added, as well as some recipes in botania tweaked to fit the skyblock.
The goal of this addon is to allow for every single item in the game to be acquired properly in a skyblock environment."

The long answer is it really helped to cut down the extra scripting required to allow access to all of the items.  It also assisted with the following:

After spawning in the Garden of Glass you'll find Living Roots below the landing area. These can be used to create Saplings and Floral Fertilizer. They also work as Bone Meal. Shift-right clicking a Dirt or Grass block with an empty hand will have you rummaging through the soil, finding some Pebbles, that can be converted into Cobblestone. Filling a Petal Apothecary can be done with a Bowl by clicking on a water block.
Aside from that, some things in Botania are different to fit the Skyblock play: The Orechid is easier to make, faster, and much cheaper; The Cocoon of Caprice and the Mana Spreader have different recipes; the Blaze Mesh, which can be used to create Obsidian, uses powder instead of rods; melon or pumpkin seeds may drop from tall grass; floral fertilizer creates more per craft, and some recipes are added.
A problem that one might face in this world is entering the Nether. Worry not, however, as Blaze Meshes, as mentioned previously, can create Obsidian. To get these lamps, creating Blazes using Fel Pumpkins might be a good investment.
Since there's no easily available Flint, opening the portal with a Fire Charge will have to do.
Aside from providing light, the Mana Flash present in the starting area allows a player who has lost their Lexica Botania to exchange a Sapling for it, by right-clicking with the Sapling on the Mana Flame.

**Comment by Ravin890** [comment]
okay that makes sense.
